### ISSUE TITLE
Can't bind to 'intercomShow' since it isn't a known property of 'button'

### ISSUE THREAD

**Issue by seigneur** [CaliStyle/angular2-intercom#21]
Using 1.0.0-beta.6 , 

Added it to app.module.ts and app.component.ts as per installation directions.

On Route change Pings are send out as well the iframe is loaded. However when I try to use the directive : <button [intercomShow]="yourMessage"></button> . I get the above error.

Uncaught Error: Template parse errors:
Can't bind to 'intercomShow' since it isn't a known property of 'button'. ("
    </div>
    <footer class="al-footer clearfix">
<button class="al-footer-right btn btn-default" [ERROR ->][intercomShow]="test"></button> 

      <!--<div class="al-footer-right" translate>{{'general.created"): ng:///PagesModule/Pages.html@10:48
    at syntaxError (compiler.es5.js:1690) [<root>]
    at TemplateParser.parse (compiler.es5.js:12811) [<root>]
    at JitCompiler._compileTemplate (compiler.es5.js:26963) [<root>]
    at :4200/vendor.bundle.js:113285:62 [<root>]
    at Set.forEach (<anonymous>) [<root>]
    at JitCompiler._compileComponents (compiler.es5.js:26883) [<root>]
    at :4200/vendor.bundle.js:113172:19 [<root>]
    at Object.then (compiler.es5.js:1679) [<root>]
    at JitCompiler._compileModuleAndComponents (compiler.es5.js:26769) [<root>]
    at JitCompiler.compileModuleAsync (compiler.es5.js:26698) [<root>]
    at PlatformRef_._bootstrapModuleWithZone (core.es5.js:4535) [<root>]
    at PlatformRef_.bootstrapModule (core.es5.js:4521) [<root>]
    at Object.373 (main.ts:10) [<root>]

**Comment by wbhob** [comment]
You need to add `IntercomModule` to your PagesModule, without `forRoot()`. That way, you can register the directives with the module without registering the Intercom provider in the child module.
